### ISSUE TITLE
/auth/signup 400 because of duplicate keys

### ISSUE THREAD

**Issue by fua0004673** [NREL/crowdsource-mask-wearing#8]
## Background

When working through the [create account workflow](https://covid.k8s.transity.io/user/register), `/auth/signup` responds with a 400 for new users. @shankari 

## Replication
Visit [this](https://covid.k8s.transity.io/user/register)

Backend responds with 400 response, with error:

```
{"error":{"message":"E11000 duplicate key error collection: default.users index: email_1 dup key: { email: null }"}}
```

Indicates that because the current account creation workflow only requires a username and password, the email field is being populated as `null` and therefore if any preexisting accounts exist, the backend will error with a `dup key`. Note this means that at most one user account can be created (with email = `null`)

**Comment by shankari** [comment]
Are you sure that the deployed backend is the most recent version?

Because I removed `email` as a field from the mongoose schema in 
https://github.com/NREL/crowdsource-mask-wearing/commit/40e3aac26f0e6ebd65283be7c89d6de58eab8b56#diff-b8851395157dd6273a2c266d223aeee0

So not only is email not required, it cannot even be provided 😄 

I also created three users (`user1`, `user2`, and `user3`) in quick succession right now and everything worked.

```
Angular is running in the development mode. Call enableProdMode() to enable the production mode. core.js:40853
Object { message: "Your account has been created successfully" }   register.component.ts:31:16
Object { message: "Your account has been created successfully" }   register.component.ts:31:16
Object { message: "Your account has been created successfully" }   register.component.ts:31:16
```

<img width="1356" alt="Screen Shot 2020-07-24 at 5 52 53 PM" src="https://user-images.githubusercontent.com/2423263/88445343-c9c44500-cdd6-11ea-96ac-988c88dd1221.png">

**Comment by fua0004673** [comment]
Oh shoot, yes that could do it. Our CD team might have not pulled your most recent changes - looping them in now and seeing what they find 😄 apologies for the confusion!
